function matlab2nexus_acquisitionInterface()
% main acquisition interface for data capture
%
% ----------------------------------------------------------------------- %
% Created: 29/11/2019
% ----------------------------------------------------------------------- %
% Simnon Thwaites
% simonthwaites1991@gmail.com
% ----------------------------------------------------------------------- %

%% Create main figure
figTag = 'acq_figTag';
udpFig = figure('numbertitle',      'off', ...
                'name',             'Matlab2Nexus Acquisition Interface', ...
                'menubar',          'none', ...
                'toolbar',          'none', ...
                'resize',           'on', ...
                'tag',              figTag, ...
                'renderer',         'painters', ...
                'units',            'normalized', ...
                'outerposition',    [0.2 0.2 0.6 0.6],...
                'HandleVisibility', 'callback'); % hide the handle to prevent unintended modifications
h = guihandles(udpFig); % create handles attached to udpFig

end