function matlab2nexus_acquisitionInterface(sessionString, pathList, trial_list)
% main acquisition interface for data capture
%
% ----------------------------------------------------------------------- %
% Created: 29/11/2019
% Updates: 5/12/2019 - previous button working
%                    - next button working
%                    - trial counters working
% ----------------------------------------------------------------------- %
% Simnon Thwaites
% simonthwaites1991@gmail.com
% ----------------------------------------------------------------------- %

%% Create main figure
figTag = 'acq_figTag';
acquisitionFig = figure('numbertitle',      'off', ...
                'name',             'Matlab2Nexus Acquisition Interface', ...
                'menubar',          'none', ...
                'toolbar',          'none', ...
                'resize',           'on', ...
                'tag',              figTag, ...
                'renderer',         'painters', ...
                'units',            'normalized', ...
                'outerposition',    [0.2 0.2 0.6 0.6],...
                'HandleVisibility', 'callback'); % hide the handle to prevent unintended modifications
h.acquisitionFig = guihandles(acquisitionFig); % create handles attached to acquisitionFig

%% define GUI object positions (x-pos,y-pos, x-width, y-height)
% staticText_backgroundColour = [0.85 0.85 0.85];
staticText_backgroundColour = [0.94 0.94 0.94];

% panel positions
trial_list_panel_position = [0.63 0.16 0.35 0.82];
session_info_panel_position = [0.02 0.85 0.6 0.13];
capture_panel_position = [0.02 0.3 0.6 0.53];
comments_panel_position = [0.02 0.02 0.6 0.26];
end_capture_panel_position = [0.63 0.02 0.35 0.12];

% session info panlel objects
sessionString_textPosition = [0.01 0.6 0.98 0.3];
pathList_textPosition = [0.01 0.05 0.98 0.3];

% comment field panel objects
comment_editField_position = [0.01 0.1 0.8 0.8];
comment_editField_staticText_position = [0.01 0.91 0.4 0.1];
comment_updateButton_position = [0.82 0.1 0.17 0.8];

% capture panel objects
nowCapturing_staticText_position = [0.01 0.91 0.2 0.07];
trialNumber_staticText_position = [0.01 0.83 0.2 0.07];
savingAs_staticText_position = [0.01 0.75 0.2 0.07];
nowCapturing_dynamicText_position = [0.21 0.91 0.5 0.07];
trialNumber_dynamicText_position = [0.21 0.83 0.5 0.07];
savingAs_dynamicText_position = [0.21 0.75 0.5 0.07];
nextTrial_staticText_position = [0.79 0.3 0.2 0.08];
previousTrial_staticText_position = [0.01 0.3 0.2 0.08];

nextTrial_button_position = [0.79 0.4 0.2 0.2];
previousTrial_button_position = [0.01 0.4 0.2 0.2];
start_button_position = [0.525 0.35 0.215 0.3];
stop_button_position = [0.26 0.35 0.215 0.3];

start_colour = [0 .8 0];
stop_colour = [.8 0 0];
leftright_colour = [0.4 0.4 0.4];
buttonFont = 16;

% trial list panel objects
trial_list_text_position = [0.01 0.01 0.8 0.98];





%% Initialise UI values
% initialise capture info
h.acquisitionFig.thisCaptureString = '<Hit Next Trial button>'; % start as empty
h.acquisitionFig.thisCaptureNumber = '00'; % start as zero
h.acquisitionFig.thisCaptureSavingAs = ''; % start empty

% create cell array from trial list
h.acquisitionFig.trialCellArray = cellstr(trial_list); 
% now create additional collumn for trial counter
h.acquisitionFig.trialCellArray = [h.acquisitionFig.trialCellArray repmat({1},size(h.acquisitionFig.trialCellArray,1),1)];
% create additional collumn for list order
h.acquisitionFig.trialCellArray = [h.acquisitionFig.trialCellArray num2cell((1:length(trial_list))')];

% trial cell array looks like:
% {full trial name}   {short trial name}  {trial ID}  {trial count}  {original trial order}

% create arrays for updated trial lists
h.acquisitionFig.trialCellArray_updated = h.acquisitionFig.trialCellArray;
% completed trials starting as empty list
h.acquisitionFig.trialCellArray_completed = cell(size(h.acquisitionFig.trialCellArray,1),...
    size(h.acquisitionFig.trialCellArray,2));
h.acquisitionFig.trialCellArray_completed_counter = 0;


%% Define UI panels
h.acquisitionFig.trial_list_panel = uipanel(acquisitionFig, ...
    'Title',        'Trial List', ...
    'FontSize',     14, ...
    'Position',     trial_list_panel_position);
h.acquisitionFig.session_info_panel = uipanel(acquisitionFig, ...
    'Title',        'Session Information', ...
    'FontSize',     14, ...
    'Position',     session_info_panel_position);
h.acquisitionFig.capture_panel = uipanel(acquisitionFig, ...
    'Title',        'Data Capture', ...
    'FontSize',     18, ...
    'Position',     capture_panel_position);
h.acquisitionFig.comments_panel = uipanel(acquisitionFig, ...
    'Title',        'Comments', ...
    'FontSize',     14, ...
    'Position',     comments_panel_position);
h.acquisitionFig.end_capture_panel = uipanel(acquisitionFig, ...
    'Title',        'End Capture Session', ...
    'FontSize',     14, ...
    'Position',     end_capture_panel_position);


%% Define UI controls

% Session info panel objects
h.acquisitionFig.sessionString_Text = uicontrol('Parent',    h.acquisitionFig.session_info_panel, ...
    'Style',                'text',...
    'Units',                'normalized', ...
    'String',               ['Session String:   ', sessionString],...
    'BackgroundColor',      staticText_backgroundColour, ...
    'Position',             sessionString_textPosition, ...
    'HorizontalAlignment',  'left');
                
h.acquisitionFig.pathList_text = uicontrol('Parent',    h.acquisitionFig.session_info_panel, ...
    'Style',                'text',...
    'Units',                'normalized', ...
    'String',               ['File Path:   ', pathList.session_dir],...
    'BackgroundColor',      staticText_backgroundColour, ...
    'Position',             pathList_textPosition, ...
    'HorizontalAlignment',  'left');
                
% comment panel objects
h.acquisitionFig.comment_editField = uicontrol('Parent', h.acquisitionFig.comments_panel, ...
    'Style',                'edit', ...
    'Units',                'normalized', ...
    'Position',             comment_editField_position, ...
    'String',               '<Press Enter after each comment change. Then commit the change with the push button to the right>',...
    'Callback',             @comment_CallBack);
h.acquisitionFig.comment_editField_staticText = uicontrol('Parent', h.acquisitionFig.comments_panel, ...
    'Style',                'text', ...
    'Units',                'normalized', ...
    'Position',             comment_editField_staticText_position, ...
    'String',               'Enter comments on trial/data capture here: ', ...
    'HorizontalAlignment',  'left');
h.acquisitionFig.comment_updateButton = uicontrol('Parent', h.acquisitionFig.comments_panel, ...
    'Style',                'pushbutton', ...
    'Units',                'normalized', ...
    'Enable',               'off', ...
    'String',               'Update Comment File', ...
    'Position',             comment_updateButton_position, ...
    'Callback',             @comment_updateButton_CallBack);
                
% trial list panel objects
h.acquisitionFig.trial_list_text = uicontrol('Parent', h.acquisitionFig.trial_list_panel, ...
    'Style',                'listbox', ...
    'Units',                'normalized', ...
    'FontSize',             12, ...
    'Position',             trial_list_text_position, ...
    'String',               h.acquisitionFig.trialCellArray(:,1));

% capture panel objects
h.acquisitionFig.nowCapturing_staticText = uicontrol('Parent',    h.acquisitionFig.capture_panel, ...
    'Style',                'text',...
    'Units',                'normalized', ...
    'String',               'Now capturing:   ',...
    'BackgroundColor',      staticText_backgroundColour, ...
    'Position',             nowCapturing_staticText_position, ...
    'HorizontalAlignment',  'left', ...
    'FontSize',             10);
h.acquisitionFig.nowCapturing_dynamicText = uicontrol('Parent',    h.acquisitionFig.capture_panel, ...
    'Style',                'text',...
    'Units',                'normalized', ...
    'String',               h.acquisitionFig.thisCaptureString,...
    'BackgroundColor',      staticText_backgroundColour, ...
    'Position',             nowCapturing_dynamicText_position, ...
    'HorizontalAlignment',  'left', ...
    'FontSize',             10);
h.acquisitionFig.trialNumber_staticText = uicontrol('Parent',    h.acquisitionFig.capture_panel, ...
    'Style',                'text',...
    'Units',                'normalized', ...
    'String',               'Trial Number:   ',...
    'BackgroundColor',      staticText_backgroundColour, ...
    'Position',             trialNumber_staticText_position, ...
    'HorizontalAlignment',  'left', ...
    'FontSize',             10);
h.acquisitionFig.trialNumber_dynamicText = uicontrol('Parent',    h.acquisitionFig.capture_panel, ...
    'Style',                'text',...
    'Units',                'normalized', ...
    'String',               h.acquisitionFig.thisCaptureNumber,...
    'BackgroundColor',      staticText_backgroundColour, ...
    'Position',             trialNumber_dynamicText_position, ...
    'HorizontalAlignment',  'left', ...
    'FontSize',             10);
h.acquisitionFig.savingAs_staticText = uicontrol('Parent',    h.acquisitionFig.capture_panel, ...
    'Style',                'text',...
    'Units',                'normalized', ...
    'String',               'Saving As:   ',...
    'BackgroundColor',      staticText_backgroundColour, ...
    'Position',             savingAs_staticText_position, ...
    'HorizontalAlignment',  'left', ...
    'FontSize',             10);
h.acquisitionFig.savingAs_dynamicText = uicontrol('Parent',    h.acquisitionFig.capture_panel, ...
    'Style',                'text',...
    'Units',                'normalized', ...
    'String',               h.acquisitionFig.thisCaptureSavingAs,...
    'BackgroundColor',      staticText_backgroundColour, ...
    'Position',             savingAs_dynamicText_position, ...
    'HorizontalAlignment',  'left', ...
    'FontSize',             10);
h.acquisitionFig.nextTrial_staticText = uicontrol('Parent',    h.acquisitionFig.capture_panel, ...
    'Style',                'text',...
    'Units',                'normalized', ...
    'String',               'Next Trial',...
    'BackgroundColor',      staticText_backgroundColour, ...
    'Position',             nextTrial_staticText_position, ...
    'FontSize',             8);
h.acquisitionFig.previousTrial_staticText = uicontrol('Parent',    h.acquisitionFig.capture_panel, ...
    'Style',                'text',...
    'Units',                'normalized', ...
    'String',               'Previous Trial',...
    'BackgroundColor',      staticText_backgroundColour, ...
    'Position',             previousTrial_staticText_position, ...
    'FontSize',             8);    
h.acquisitionFig.nextTrial_button = uicontrol('Parent',    h.acquisitionFig.capture_panel, ...
    'unit',                 'normalized',...
    'style',                'pushbutton',...
    'BackgroundColor',      leftright_colour,...
    'string',               '>>>',...
    'FontSize',             buttonFont, ...
    'position',             nextTrial_button_position,...
    'enable',               'on', ...
    'callback',             @nextTrial_button_CallBack);
h.acquisitionFig.previousTrial_button = uicontrol('Parent',    h.acquisitionFig.capture_panel, ...
    'unit',                 'normalized',...
    'style',                'pushbutton',...
    'BackgroundColor',      leftright_colour,...
    'string',               '<<<',...
    'FontSize',             buttonFont, ...
    'position',             previousTrial_button_position,...
    'enable',               'off', ...
    'callback',             @previousTrial_button_CallBack);
h.acquisitionFig.start_button = uicontrol('Parent',    h.acquisitionFig.capture_panel, ...
    'unit',                 'normalized',...
    'style',                'pushbutton',...
    'BackgroundColor',      start_colour,...
    'string',               'START',...
    'FontSize',             buttonFont, ...
    'position',             start_button_position,...
    'enable',               'off', ...
    'callback',             @start_button_CallBack);
h.acquisitionFig.stop_button = uicontrol('Parent',    h.acquisitionFig.capture_panel, ...
    'unit',                 'normalized',...
    'style',                'pushbutton',...
    'BackgroundColor',      stop_colour,...
    'string',               'STOP',...
    'FontSize',             buttonFont, ...
    'position',             stop_button_position,...
    'enable',               'off', ...
    'callback',             @stop_button_CallBack);
 
guidata(acquisitionFig,h.acquisitionFig);

end

%% CALLBACKS
function comment_CallBack(text_object, ~, ~)
h.acquisitionFig = guidata(text_object);
set(h.acquisitionFig.comment_updateButton, 'Enable', 'on');
guidata(text_object, h.acquisitionFig) % update handles
end

function comment_updateButton_CallBack(pushButton_object, ~, ~)
h.acquisitionFig = guidata(pushButton_object);
h.acquisitionFig.commentString = h.acquisitionFig.comment_editField.String;
set(h.acquisitionFig.comment_updateButton, 'Enable', 'off');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% need to save this comment field somewhere!!
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

guidata(pushButton_object, h.acquisitionFig) % update handles
end

function nextTrial_button_CallBack(pushButton_object, ~, ~)
h.acquisitionFig = guidata(pushButton_object);

% need to have a counter here for the completed cell array
h.acquisitionFig.trialCellArray_completed_counter = h.acquisitionFig.trialCellArray_completed_counter + 1;
counter = h.acquisitionFig.trialCellArray_completed_counter;

if counter < length(h.acquisitionFig.trialCellArray) + 1
    % get next capture info
    h.acquisitionFig.thisCaptureString = h.acquisitionFig.trialCellArray_updated(1,1); % get the next trial from top of trial_list_updated
    h.acquisitionFig.thisCaptureNumber = num2str(h.acquisitionFig.trialCellArray_updated{1,4}, '%02.f'); % get the capture number
    h.acquisitionFig.thisCaptureSavingAs = [h.acquisitionFig.trialCellArray_updated{1,2},'_',h.acquisitionFig.thisCaptureNumber]; % generate the Saving As string
    % update the fields
    set(h.acquisitionFig.nowCapturing_dynamicText, 'String', h.acquisitionFig.thisCaptureString);
    set(h.acquisitionFig.trialNumber_dynamicText, 'String', h.acquisitionFig.thisCaptureNumber);
    set(h.acquisitionFig.savingAs_dynamicText, 'String', h.acquisitionFig.thisCaptureSavingAs);
    
    % remove the current capture from the trial list panel and add to completed
    % list
    h.acquisitionFig.trialCellArray_completed(h.acquisitionFig.trialCellArray_updated{1,5},:) = h.acquisitionFig.trialCellArray_updated(1,:); % add the top of trial list to completed array
    h.acquisitionFig.trialCellArray_updated(1,:) = [];  % remove the top element of the trial list
    set(h.acquisitionFig.trial_list_text, 'String', h.acquisitionFig.trialCellArray_updated(:,1)); % update trial list
    set(h.acquisitionFig.start_button, 'enable', 'on'); % enable start button
    set(h.acquisitionFig.previousTrial_button, 'enable', 'on'); % enable previous trial button
    
    % once you reach end of the trial list, disable the next trial button
    if counter == length(h.acquisitionFig.trialCellArray)
        set(h.acquisitionFig.nextTrial_button, 'enable', 'off');
    end
end
guidata(pushButton_object, h.acquisitionFig) % update handles
end

function previousTrial_button_CallBack(pushButton_object, ~, ~)
h.acquisitionFig = guidata(pushButton_object);

% create counter
counter = h.acquisitionFig.trialCellArray_completed_counter;

if counter ~= 0
    % the row to shift should be one with largest value in 5 collumn
    shift_row_num = max(cell2mat(h.acquisitionFig.trialCellArray_completed(:,5)));
    
    if counter < length(h.acquisitionFig.trialCellArray)+1
        set(h.acquisitionFig.nextTrial_button, 'enable', 'on');
    end
    
    % update the trial list
    h.acquisitionFig.trialCellArray_updated = [h.acquisitionFig.trialCellArray_completed(shift_row_num,:); h.acquisitionFig.trialCellArray_updated];
    set(h.acquisitionFig.trial_list_text, 'String', h.acquisitionFig.trialCellArray_updated(:,1));
    h.acquisitionFig.trialCellArray_completed(shift_row_num,:) = []; % then make the shifted row empty
    
    % decrease the counter
    counter = counter - 1;
    h.acquisitionFig.trialCellArray_completed_counter = counter;
    
    % once get back to zero, disable previous button
    if counter == 0
        set(h.acquisitionFig.previousTrial_button, 'enable', 'off');
        set(h.acquisitionFig.start_button, 'enable', 'off');
        set(h.acquisitionFig.nextTrial_button, 'enable', 'on');
        % update the fields back to starting values
        set(h.acquisitionFig.nowCapturing_dynamicText, 'String', '<Hit Next Trial button>');
        set(h.acquisitionFig.trialNumber_dynamicText, 'String', '00');
        set(h.acquisitionFig.savingAs_dynamicText, 'String', '');
    else
        % update capture info
        h.acquisitionFig.thisCaptureString = h.acquisitionFig.trialCellArray_completed(shift_row_num-1,1); % get the next trial from top of trial_list_updated
        h.acquisitionFig.thisCaptureNumber = num2str(h.acquisitionFig.trialCellArray_completed{shift_row_num-1,4}, '%02.f'); % get the capture number
        h.acquisitionFig.thisCaptureSavingAs = [h.acquisitionFig.trialCellArray_completed{shift_row_num-1,2},'_',h.acquisitionFig.thisCaptureNumber]; % generate the Saving As string
        % update the fields
        set(h.acquisitionFig.nowCapturing_dynamicText, 'String', h.acquisitionFig.thisCaptureString);
        set(h.acquisitionFig.trialNumber_dynamicText, 'String', h.acquisitionFig.thisCaptureNumber);
        set(h.acquisitionFig.savingAs_dynamicText, 'String', h.acquisitionFig.thisCaptureSavingAs);
    end
else
    % if back to start of trial list, disble previous button
    set(h.acquisitionFig.previousTrial_button, 'enable', 'off');
end
guidata(pushButton_object, h.acquisitionFig) % update handles
end

function start_button_CallBack(pushButton_object, ~, ~)
h.acquisitionFig = guidata(pushButton_object);

% disble all buttons including start
set(h.acquisitionFig.previousTrial_button, 'enable', 'off');
set(h.acquisitionFig.start_button, 'enable', 'off');
set(h.acquisitionFig.nextTrial_button, 'enable', 'off'); 

% enable stop button
set(h.acquisitionFig.stop_button, 'enable', 'on');

% send the udp packet

guidata(pushButton_object, h.acquisitionFig) % update handles
end

function stop_button_CallBack(pushButton_object, ~, ~)
h.acquisitionFig = guidata(pushButton_object);

counter = h.acquisitionFig.trialCellArray_completed_counter;

% send the udp packet

% disable stop button
set(h.acquisitionFig.stop_button, 'enable', 'off');

% enable all other buttons
if counter > 0 && counter < length(h.acquisitionFig.trialCellArray) + 1
    set(h.acquisitionFig.nextTrial_button, 'enable', 'on');
    set(h.acquisitionFig.start_button, 'enable', 'on');
    set(h.acquisitionFig.previousTrial_button, 'enable', 'on');
    if counter == length(h.acquisitionFig.trialCellArray)
        set(h.acquisitionFig.nextTrial_button, 'enable', 'off');
        set(h.acquisitionFig.previousTrial_button, 'enable', 'on');
        set(h.acquisitionFig.start_button, 'enable', 'on');
    end
end

if counter == 0    
    set(h.acquisitionFig.previousTrial_button, 'enable', 'off');
    set(h.acquisitionFig.start_button, 'enable', 'off');
    set(h.acquisitionFig.nextTrial_button, 'enable', 'on');
end

% update trial counters
add_trial_num_to = max(cell2mat(h.acquisitionFig.trialCellArray_completed(:,5)));
h.acquisitionFig.trialCellArray_completed{add_trial_num_to,4} = h.acquisitionFig.trialCellArray_completed{add_trial_num_to,4} + 1;
h.acquisitionFig.thisCaptureNumber = num2str(h.acquisitionFig.trialCellArray_completed{add_trial_num_to,4}, '%02.f');
h.acquisitionFig.thisCaptureSavingAs = [h.acquisitionFig.trialCellArray_completed{add_trial_num_to,2},'_',h.acquisitionFig.thisCaptureNumber]; % generate the Saving As string
set(h.acquisitionFig.trialNumber_dynamicText, 'String', h.acquisitionFig.thisCaptureNumber);
set(h.acquisitionFig.savingAs_dynamicText, 'String', h.acquisitionFig.thisCaptureSavingAs);

guidata(pushButton_object, h.acquisitionFig) % update handles
end